### ISSUE TITLE
Feature: User is able to Log into the support Chat App

### ISSUE THREAD

**Issue by bhaisingh** [bhaisingh/chat-app#1]
## ⚙️ Feature # 1

> ##### What capability will users have when this feature is merged?

User is able to connect and Log into the support Chat App

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will enter user-id and password to enter Chat room for support

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/20628519/143455492-ce19accf-0378-412d-9436-da0616e22b99.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [ ] Update `schema.sql` to create initial database
- [ ] Update `data.sql` to create a list of user and setup their password for access

### ☁️ Server

- [ ] Update `server/index.js` to add new user and password
- [ ] Update server/index.js' to authenticate user against the stored user-id and password
- [ ] Create middleware for error processing
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client

- [ ] Create home component 
- [ ] Update App component with componentDidMount to store the initial stage of props.
- [ ] Update App component to render the login Page
- [ ] Style the page Header, Body , Footer (Desktop and mobile)

### 🧑‍⚕️ Clean Up

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
