### ISSUE TITLE
Feature: User is able to choose a support channel

### ISSUE THREAD

**Issue by bhaisingh** [bhaisingh/chat-app#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to choose from 2 support channel (Self Serve or Live Support)

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Once logged in user will have the option to choose from 2 channels #Self Serve , # Live support. The user will be put in the chosen chat room.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/20628519/143516163-a8b989af-3a0d-4330-bb6e-5ef903f4b264.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [ ] Update `server/index.js` to add a `post /api/userSession`
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client

- [ ] Update the App component to handle the `click` event
     - [ ] To select the Chat channel.
     - [ ] To log-out of the Chat channel
- [ ] Create a component  `self serve`
     - [ ]  render with the Initial menu selection.
- [ ] Create a  component `Live Support` 
     - [ ]  render with the Initial greeting.
- [ ] create a component `log-out`
     - [ ] Update log-out timestamp.
     - [ ] Navigate back to `Log-in` screen
- [ ] Update `componentDidMount` to:
     - [ ]  update the state of the channel selected.

### 🧑‍⚕️ Clean Up

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
